//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RED2.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RED2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Search again 的本地化字符串。
        /// </summary>
        internal static string btn_scan_again {
            get {
                return ResourceManager.GetString("btn_scan_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleted {0} empty directories (Failed: {1}, Skipped: {2}, Runtime: {3:D2}:{4:D2} min) 的本地化字符串。
        /// </summary>
        internal static string delete_process_finished {
            get {
                return ResourceManager.GetString("delete_process_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete process was aborted. 的本地化字符串。
        /// </summary>
        internal static string deletion_aborted {
            get {
                return ResourceManager.GetString("deletion_aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: 的本地化字符串。
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The path you picked is not a directory or does not exist. 的本地化字符串。
        /// </summary>
        internal static string error_dir_does_not_exist {
            get {
                return ResourceManager.GetString("error_dir_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore file settings are in a bad format 的本地化字符串。
        /// </summary>
        internal static string error_ignore_settings {
            get {
                return ResourceManager.GetString("error_ignore_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only one directory can be accepted. 的本地化字符串。
        /// </summary>
        internal static string error_only_one_folder {
            get {
                return ResourceManager.GetString("error_only_one_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found {0} empty directories (Checked: {1} / Runtime: {2:D2}:{3:D2} min) 的本地化字符串。
        /// </summary>
        internal static string found_x_empty_folders {
            get {
                return ResourceManager.GetString("found_x_empty_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contains &quot;trash&quot; 的本地化字符串。
        /// </summary>
        internal static string icon_contains_trash {
            get {
                return ResourceManager.GetString("icon_contains_trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty 的本地化字符串。
        /// </summary>
        internal static string icon_default {
            get {
                return ResourceManager.GetString("icon_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleted 的本地化字符串。
        /// </summary>
        internal static string icon_deleted_folder {
            get {
                return ResourceManager.GetString("icon_deleted_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hidden 的本地化字符串。
        /// </summary>
        internal static string icon_hidden_folder {
            get {
                return ResourceManager.GetString("icon_hidden_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Locked 的本地化字符串。
        /// </summary>
        internal static string icon_locked_folder {
            get {
                return ResourceManager.GetString("icon_locked_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protected 的本地化字符串。
        /// </summary>
        internal static string icon_protected_folder {
            get {
                return ResourceManager.GetString("icon_protected_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root 的本地化字符串。
        /// </summary>
        internal static string icon_root {
            get {
                return ResourceManager.GetString("icon_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        internal static string icon_warning {
            get {
                return ResourceManager.GetString("icon_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the directory that you want to be cleaned 的本地化字符串。
        /// </summary>
        internal static string please_select {
            get {
                return ResourceManager.GetString("please_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process was aborted 的本地化字符串。
        /// </summary>
        internal static string process_aborted {
            get {
                return ResourceManager.GetString("process_aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process was cancelled 的本地化字符串。
        /// </summary>
        internal static string process_cancelled {
            get {
                return ResourceManager.GetString("process_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RED deleted {0} empty directories for you since you installed it :) 的本地化字符串。
        /// </summary>
        internal static string red_deleted {
            get {
                return ResourceManager.GetString("red_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleting empty directories ({0} of {1}) 的本地化字符串。
        /// </summary>
        internal static string removing_empty_folders {
            get {
                return ResourceManager.GetString("removing_empty_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scanning directories... 的本地化字符串。
        /// </summary>
        internal static string scanning_folders {
            get {
                return ResourceManager.GetString("scanning_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Searching empty directories... 的本地化字符串。
        /// </summary>
        internal static string searching_empty_folders {
            get {
                return ResourceManager.GetString("searching_empty_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Started deletion process... 的本地化字符串。
        /// </summary>
        internal static string started_deletion_process {
            get {
                return ResourceManager.GetString("started_deletion_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning! 的本地化字符串。
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning, do you want to delete empty system directories? This may harm your operating system. 的本地化字符串。
        /// </summary>
        internal static string warning_really_delete {
            get {
                return ResourceManager.GetString("warning_really_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \&quot;{0}\&quot; folder skipped because creation time [{2}] is &lt; {1} hours old 的本地化字符串。
        /// </summary>
        internal static string young_folder_skipped {
            get {
                return ResourceManager.GetString("young_folder_skipped", resourceCulture);
            }
        }
    }
}
